# Deploys Folders in GCP with Terraform
name: 'GCP Folders'

on:
  pull_request:
    paths:
      - 'environment/foundation/1-org-b/1-org-b.tfvars'
      - 'environemnt/foundation/1-org-b/variables.tf'
  push:
    paths:
      - 'environment/foundation/1-org-b/1-org-b.tfvars'
      - 'environemnt/foundation/1-org-b/variables.tf'
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./environment/foundation/1-org-b/

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: GCP login
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '319.0.0'
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # Installs terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.5

    # Checks for proper formatting in terraform code
    - name: Terraform Fmt
      run: terraform fmt

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend-config=bucket=${{ secrets.TERRAFORM_STATE_BUCKET }} -backend-config=prefix=foundation/1-org-b

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Validate
      run: terraform validate

    # Generates terraform execution plan
    - name: Terraform Plan
      run: terraform plan -var-file=1-org-b.tfvars -no-color

    # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -var-file=1-org-b.tfvars -refresh=false -auto-approve
